[debug] [2024-12-29T09:02:58.569Z] ----------------------------------------------------------------------
[debug] [2024-12-29T09:02:58.574Z] Command:       /home/sanjay/.nvm/versions/node/v20.11.1/bin/node /home/sanjay/.nvm/versions/node/v20.11.1/bin/firebase deploy --only hosting:srh-agency
[debug] [2024-12-29T09:02:58.575Z] CLI Version:   13.15.2
[debug] [2024-12-29T09:02:58.576Z] Platform:      linux
[debug] [2024-12-29T09:02:58.577Z] Node Version:  v20.11.1
[debug] [2024-12-29T09:02:58.577Z] Time:          Sun Dec 29 2024 14:32:58 GMT+0530 (India Standard Time)
[debug] [2024-12-29T09:02:58.578Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-12-29T09:02:58.724Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-12-29T09:02:58.725Z] > authorizing via signed-in user (sanjaygoswami60@gmail.com)
[debug] [2024-12-29T09:02:58.726Z] [iam] checking project shicane for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-12-29T09:02:58.728Z] > refreshing access token with scopes: []
[debug] [2024-12-29T09:02:58.730Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-12-29T09:02:58.731Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-12-29T09:03:10.151Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------922023511704480340214729","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com
[debug] [2024-12-29T09:03:10.152Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-12-29T09:03:10.153Z] > refreshing access token with scopes: []
[debug] [2024-12-29T09:03:10.153Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-12-29T09:03:10.154Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-12-29T09:03:22.437Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------967298170993284727120047","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com
[debug] [2024-12-29T09:03:22.438Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[info] 
[info] === Deploying to 'shicane'...
[info] 
[info] i  deploying hosting 
[debug] [2024-12-29T09:03:22.447Z] > refreshing access token with scopes: []
[debug] [2024-12-29T09:03:22.449Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-12-29T09:03:22.449Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-12-29T09:03:34.731Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------123251214908133367624593","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo EAI_AGAIN www.googleapis.com
[debug] [2024-12-29T09:03:39.740Z] Error: Timed out.
    at Timeout._onTimeout (/home/sanjay/.nvm/versions/node/v20.11.1/lib/node_modules/firebase-tools/lib/utils.js:268:49)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[error] 
[error] Error: An unexpected error has occurred.
